language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  global:
    - PLUGIN_NAME=CakeResque
    - REQUIRE=""
    - PHPREDIS_VERSION=2.2.4
    - DB=mysql CAKE_VERSION=2.4
  matrix:
    - DB=mysql CAKE_VERSION=2.2
    - DB=mysql CAKE_VERSION=2.3
    - DB=mysql CAKE_VERSION=2.4
    - DB=mysql CAKE_VERSION=2.5

matrix:
  include:
    - php: 5.4
      env:
        - COVERALLS=1
    - php: 5.4
      env:
        - PHPCS=1
    - php: 5.4
      env:
        - FOC_VALIDATE=1

services:
  - redis-server

before_script:
  - wget https://github.com/nicolasff/phpredis/archive/$PHPREDIS_VERSION.zip -O php-redis.zip
  - unzip php-redis.zip
  - cd phpredis-$PHPREDIS_VERSION/
  - phpize
  - ./configure
  - make && make install
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - cd ../
  - rm -R phpredis-$PHPREDIS_VERSION/
  - git clone -b master https://github.com/FriendsOfCake/travis.git --depth 1 ../travis
  - echo "

  require dirname(__DIR__) . '/Vendor/autoload.php';" >> ../cakephp/app/Config/core.php
  - ../travis/before_script.sh

script:
  - ../travis/script.sh

after_success:
  - ../travis/after_success.sh

notifications:
  email: false
