language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

env:
  global:
    - PLUGIN_NAME=CakeResque
    - REQUIRE=""
    - DB=mysql CAKE_VERSION=3.0
  matrix:
    - DB=mysql CAKE_VERSION=3.0
    - DB=mysql CAKE_VERSION=master

matrix:
  include:
    - php: 5.4
      env:
        - COVERALLS=1
    - php: 7.0
      env:
        - PHPCS=1
    - php: 5.4
      env:
        - FOC_VALIDATE=1

services:
  - redis-server

before_script:
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - git clone -b master https://github.com/FriendsOfCake/travis.git --depth 1 ../travis
  - ../travis/before_script.sh

script:
  - ../travis/script.sh

after_success:
  - ../travis/after_success.sh

notifications:
  email: false
