language: php

php:
  - 5.3
  - 5.4

env:
  - CAKE_VERSION=2.2.7 DB=mysql
  - CAKE_VERSION=master DB=mysql
  - CAKE_VERSION=2.4 DB=mysql

before_script:
  - git clone git://github.com/cakephp/cakephp ../cakephp && cd ../cakephp && git checkout $CAKE_VERSION
  - cp -R ../Cake-Resque app/Plugin/CakeResque
  - chmod -R 777 ../cakephp/app/tmp
  - set +H
  - echo "

    CakePlugin::loadAll(array('CakeResque' => array('bootstrap' => true)));" >> ../cakephp/app/Config/bootstrap.php
  - cd app/Plugin/CakeResque
  - composer self-update
  - composer install --prefer-source
  - cd ../../Console

script:
  - ./cake test CakeResque AllCakeResque --stderr